### PR TITLE
Limit zero padding for analysis_assim

### PR DESCRIPTION
**Pull request by RohanSunkarapalli**
I've added an if condition for the run_type = analysis_assim. I believe this way would help us to limit the zero padding

### CODE REVIEW

**Comment by RohanSunkarapalli** [comment]
@jameshalgren

**Review by jameshalgren — CHANGES_REQUESTED** [review]
Thanks for working on this issue. 

Will you please resubmit with some demonstration of the corrected output showing in the PR conversation? (It would also be helpful if only the relevant commits are included.)

Thanks!

@karnesh -- will you watch for the update and do further review?

**Comment by karnesh** [comment]
@jameshalgren  Sure. I can do further review.

**Comment by JordanLaserGit** [comment]
Can this be merged? We need this PR in order for datastream to process analysis_assim and analysis_assim_extended forcings.

**Comment by jameshalgren** [comment]
Replaced by #64

**Pull request closed without merging**
